name: space_chicken
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flame: ^1.37.0
  shared_preferences: ^2.5.4
  just_audio: ^0.10.5
  flutter_svg: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/winner.png
    - assets/images/winner_banner.png
    - assets/icons/
    - assets/music/button_sound_effect.mp3
    - assets/music/music_for_game.m4a
    - assets/music/muve_sound.mp3