name: space_chicken
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flame: ^1.37.0
  shared_preferences: ^2.5.4
  just_audio: ^0.10.5
  flutter_svg: ^2.3.0
  google_fonts: ^8.1.0
  connectivity_plus: ^7.1.1
  internet_connection_checker_plus: ^3.1.0
  url_launcher: ^6.3.2
  appsflyer_sdk: ^6.18.0
  firebase_core: ^4.11.0
  firebase_messaging: ^16.4.1
  webview_flutter: ^4.14.0
  webview_flutter_android: ^4.10.11
  file_selector: ^1.0.3
  http: ^1.6.0
  package_info_plus: ^10.1.0
  flutter_local_notifications: ^22.0.1
  firebase_analytics: ^12.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:

  uses-material-design: true

  assets:
    - assets/images/500_error.png
    - assets/images/Allow notifications about bonuses and promos.png
    - assets/images/Allow notifications about bonuses and promos_2.png
    - assets/images/back.png
    - assets/images/back_to_menu.png
    - assets/images/Background 2.jpg
    - assets/images/Background_game_over.png
    - assets/images/Background_settings.png
    - assets/images/Background_start_menu.jpg
    - assets/images/BGforNotifications.jpg
    - assets/images/BGforNotifications_gorezantal.jpg
    - assets/images/btton_on.png
    - assets/images/button_back.png
    - assets/images/button_off.png
    - assets/images/Cutout 1.png
    - assets/images/egg_junior.png
    - assets/images/egg_middle.png
    - assets/images/egg_super.png
    - assets/images/game_over.png
    - assets/images/game_over_box.png
    - assets/images/general_shot.png
    - assets/images/gold_egg_for_number.png
    - assets/images/Home.png
    - assets/images/Left.png
    - assets/images/loading.png
    - assets/images/Logo_master.png
    - assets/images/logout.png
    - assets/images/Music.png
    - assets/images/object_for_line.png
    - assets/images/obstacles_1.png
    - assets/images/obstacles_2.png
    - assets/images/obstacles_3.png
    - assets/images/obstacles_4.png
    - assets/images/Privacy Policy.png
    - assets/images/Rectangle 4076_2.png
    - assets/images/Rectangle 4077.png
    - assets/images/Right.png
    - assets/images/Setting_button.png
    - assets/images/settings.png
    - assets/images/settings_contaner.png
    - assets/images/settings_text.png
    - assets/images/Sound.png
    - assets/images/start_again.png
    - assets/images/Stay tuned with best offers from our casino.png
    - assets/images/Stay tuned with best offers from our casino_2.png
    - assets/images/Support.png
    - assets/images/winner.png
    - assets/images/winner_banner.png
    - assets/music/button_sound_effect.mp3
    - assets/music/music_for_game.m4a
    - assets/music/muve_sound.mp3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/Icon_Android.png
  adaptive_icon_background: "#050713"
  adaptive_icon_foreground: assets/images/Icon_Android.png
